# -*- coding: utf-8 -*-
"""Bank_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ohStI7OZCH55gaLu3ADTWYAH_Ka2kEwg

# **IMPORTING THE LIBRARIES**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning/Bank Analysis/bank.csv')
df1.head()

"""# **CHECKING THE NULL VALUE**"""

df1.isna().sum()

"""# **CATEGORICAL COLUMN VISUALIZAION**"""

cat_cols = ["job","marital","education","default","housing","loan","contact","month","poutcome"]
# 3X3 SUBPLOTS
fig, axs = plt.subplots(3,3, figsize=(20,15))
fig.tight_layout(pad=10)
fig.subplots_adjust(wspace = 0.2, hspace=0.7)
count=0
for cat_col in cat_cols:
  value_count = df1[cat_col].value_counts()
  value_count_index = value_count.index
  value_count_value = value_count.values

  i = count//3
  j = count%3
  count+=1

  axs[i,j].bar(value_count_index, value_count_value)
  axs[i,j].set_title(f"{cat_col}".upper(), fontdict={"fontsize":20, "fontweight":"bold"})

  
  for xtick in axs[i,j].get_xticklabels():
    xtick.set_rotation(90)
    xtick.set_size(12)

"""# **NUMERICAL COLUMN VISUALIZATION**"""

df1.info()

int_cols = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
fig, axs = plt.subplots(3,3, figsize=(20,15))
fig.tight_layout(pad=5)

count = 0
for int_col in int_cols:
  value_counts = df1[int_col].value_counts()
  value_count_index = value_counts.index
  value_count_value = value_counts.values

  i = count//3
  j = count%3

  count+=1

  axs[i,j].hist(df1[int_col], ec="white") 
  axs[i,j].set_title(int_col.upper(), fontdict={'fontsize':20,'fontweight': 'bold'})

  for xtick in axs[i,j].get_xticklabels():
    xtick.set_size(12)
  for ytick in axs[i,j].get_yticklabels():
    ytick.set_size(12)

"""**CONCLUSION: From above figure we can see that "Campaign", "Pdays", "Previous" columns in the dataset have outliers.**"""

df1.head()

"""# **JOB AND DEPOSIT RELATION**"""

df1['job'].unique()

df1['deposit'].unique()

df2 = pd.DataFrame()

df2['job_deposit_yes'] = df1.loc[df1["deposit"]=='yes']['job'].value_counts()
df2['job_deposit_no'] = df1.loc[df1["deposit"]=='no']['job'].value_counts()
df2.head()

plt.figure(figsize=(10,10))
df2.plot.bar(title="Job and deposit", )

# It seems that people entiteling 'blue collar', and 'service' are less likely to deposit in bank.

"""# **MARITAL AND DEPOSIT RELATION**"""

df2 = pd.DataFrame()

df2['yes_marital'] = df1.loc[df1['deposit']=='yes']['marital'].value_counts()
df2['no_marital'] = df1.loc[df1['deposit']=='no']['marital'].value_counts()
df2.head()

df2.plot.bar(title="Marital and deposit")

#CONCLUSION
# It seems that when people get married they tend to deposit less in bank.
# Single people deposite more in bank.

